// <auto-generated />
using System;
using Healthify.Platform.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Healthify.Platform.Shared.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904062549_CareRelationship_InitialCreate")]
    partial class CareRelationship_InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Healthify.Platform.CareRelationship.Domain.Model.Aggregates.CareLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("ConsentGranted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("consent_granted");

                    b.Property<DateTimeOffset?>("ConsentGrantedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("consent_granted_at");

                    b.Property<string>("ConsentScope")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("consent_scope");

                    b.Property<DateTimeOffset?>("ConsentWithdrawnAt")
                        .HasColumnType("datetime")
                        .HasColumnName("consent_withdrawn_at");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DischargeReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("discharge_reason");

                    b.Property<DateTimeOffset?>("DischargedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("discharged_at");

                    b.Property<DateTimeOffset>("EstablishedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("established_at");

                    b.Property<int?>("LastAcknowledgedVersion")
                        .HasColumnType("int")
                        .HasColumnName("last_acknowledged_version");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<int?>("PendingTargetsVersion")
                        .HasColumnType("int")
                        .HasColumnName("pending_targets_version");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("int")
                        .HasColumnName("practitioner_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_care_links");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_care_links_patient_id");

                    b.HasIndex("PractitionerId")
                        .HasDatabaseName("ix_care_links_practitioner_id");

                    b.ToTable("care_links", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.CareRelationship.Domain.Model.Aggregates.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expired_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<int>("IssuedBy")
                        .HasColumnType("int")
                        .HasColumnName("issued_by");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("redeemed_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_invitations");

                    b.HasIndex("IssuedBy")
                        .HasDatabaseName("ix_invitations_issued_by");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_invitations_token");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int>("FailedSignInAttempts")
                        .HasColumnType("int")
                        .HasColumnName("failed_sign_in_attempts");

                    b.Property<DateTimeOffset?>("LockedOutAt")
                        .HasColumnType("datetime")
                        .HasColumnName("locked_out_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.Iam.Domain.Model.Aggregates.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("NavigationShell")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("navigation_shell");

                    b.Property<string>("RoleClaim")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role_claim");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset?>("TerminatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("terminated_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.ToTable("user_sessions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
