// <auto-generated />
using System;
using Healthify.Platform.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Healthify.Platform.Shared.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006150715_Iam_AddRefreshTokenRotatedAt")]
    partial class Iam_AddRefreshTokenRotatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Healthify.Platform.CareRelationship.Domain.Model.Aggregates.CareLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("ConsentGranted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("consent_granted");

                    b.Property<DateTimeOffset?>("ConsentGrantedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("consent_granted_at");

                    b.Property<string>("ConsentScope")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("consent_scope");

                    b.Property<DateTimeOffset?>("ConsentWithdrawnAt")
                        .HasColumnType("datetime")
                        .HasColumnName("consent_withdrawn_at");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DischargeReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("discharge_reason");

                    b.Property<DateTimeOffset?>("DischargedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("discharged_at");

                    b.Property<DateTimeOffset>("EstablishedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("established_at");

                    b.Property<DateTimeOffset?>("LastAcknowledgedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_acknowledged_at");

                    b.Property<int?>("LastAcknowledgedVersion")
                        .HasColumnType("int")
                        .HasColumnName("last_acknowledged_version");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<int?>("PendingTargetsVersion")
                        .HasColumnType("int")
                        .HasColumnName("pending_targets_version");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("int")
                        .HasColumnName("practitioner_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_care_links");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_care_links_patient_id");

                    b.HasIndex("PractitionerId")
                        .HasDatabaseName("ix_care_links_practitioner_id");

                    b.ToTable("care_links", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.CareRelationship.Domain.Model.Aggregates.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expired_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<int>("IssuedBy")
                        .HasColumnType("int")
                        .HasColumnName("issued_by");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("redeemed_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_invitations");

                    b.HasIndex("IssuedBy")
                        .HasDatabaseName("ix_invitations_issued_by");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_invitations_token");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.FoodCatalog.Domain.Model.Aggregates.ReferenceFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("CarbGPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("carb_g_per_100g");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EnergyKcalPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("energy_kcal_per_100g");

                    b.Property<decimal>("FatGPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("fat_g_per_100g");

                    b.Property<bool>("IsLocalOverride")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_local_override");

                    b.Property<string>("LocalNameText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("local_name");

                    b.Property<decimal>("ProteinGPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("protein_g_per_100g");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_reference_foods");

                    b.HasIndex("LocalNameText")
                        .HasDatabaseName("ix_reference_foods_local_name");

                    b.HasIndex("SourceHash")
                        .IsUnique()
                        .HasDatabaseName("ix_reference_foods_source_hash");

                    b.ToTable("reference_foods", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int>("FailedSignInAttempts")
                        .HasColumnType("int")
                        .HasColumnName("failed_sign_in_attempts");

                    b.Property<string>("FamilyNames")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("family_names");

                    b.Property<string>("GivenNames")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("given_names");

                    b.Property<DateTimeOffset?>("LockedOutAt")
                        .HasColumnType("datetime")
                        .HasColumnName("locked_out_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("es")
                        .HasColumnName("preferred_language");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.Iam.Domain.Model.Aggregates.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("NavigationShell")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("navigation_shell");

                    b.Property<string>("PreviousRefreshTokenHash")
                        .HasColumnType("char(64)")
                        .HasColumnName("previous_refresh_token_hash");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<string>("RefreshTokenHash")
                        .IsConcurrencyToken()
                        .HasColumnType("char(64)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTimeOffset?>("RefreshTokenRotatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("refresh_token_rotated_at");

                    b.Property<string>("RoleClaim")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role_claim");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset?>("TerminatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("terminated_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_sessions");

                    b.HasIndex("PreviousRefreshTokenHash")
                        .HasDatabaseName("ix_user_sessions_previous_refresh_token_hash");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_user_sessions_refresh_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.IntakeBodyResponse.Domain.Model.Aggregates.ActiveTargetsCache", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<decimal>("CarbG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("carb_g");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EnergyKcal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("energy_kcal");

                    b.Property<decimal>("FatG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("fat_g");

                    b.Property<string>("PatientMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("patient_message");

                    b.Property<int>("PlanVersion")
                        .HasColumnType("int")
                        .HasColumnName("plan_version");

                    b.Property<decimal>("ProteinG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("protein_g");

                    b.Property<DateTimeOffset>("RefreshedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("refreshed_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("datetime")
                        .HasColumnName("valid_from");

                    b.Property<string>("_changesFromPrevious")
                        .HasColumnType("json")
                        .HasColumnName("changes_from_previous");

                    b.Property<string>("_guidelineItems")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("guideline_items");

                    b.Property<string>("_guidelines")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("guidelines");

                    b.Property<string>("_legacyRestrictions")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("legacy_restrictions");

                    b.Property<string>("_restrictions")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("restrictions");

                    b.HasKey("PatientId")
                        .HasName("p_k_active_targets_caches");

                    b.ToTable("active_targets_caches", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.IntakeBodyResponse.Domain.Model.Aggregates.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientEntryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("client_entry_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("confirmed_at");

                    b.Property<decimal?>("ConfirmedPortionGrams")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("confirmed_portion_grams");

                    b.Property<int?>("ConfirmedReferenceFoodId")
                        .HasColumnType("int")
                        .HasColumnName("confirmed_reference_food_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LocalTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("local_timestamp");

                    b.Property<int>("LocalUtcOffsetMinutes")
                        .HasColumnType("int")
                        .HasColumnName("local_utc_offset_minutes");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<string>("PhotoRef")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("photo_ref");

                    b.Property<string>("PlanAdherence")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("plan_adherence")
                        .HasDefaultValueSql("'NotAnswered'");

                    b.Property<decimal?>("ProposedConfidence")
                        .HasColumnType("decimal(6,4)")
                        .HasColumnName("proposed_confidence");

                    b.Property<DateTimeOffset?>("ProposedEstimatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("proposed_estimated_at");

                    b.Property<decimal?>("ProposedPortionGrams")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("proposed_portion_grams");

                    b.Property<int?>("ProposedReferenceFoodId")
                        .HasColumnType("int")
                        .HasColumnName("proposed_reference_food_id");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("provenance");

                    b.Property<string>("SyncState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sync_state");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_diary_entries");

                    b.HasIndex("ClientEntryId")
                        .IsUnique()
                        .HasDatabaseName("ix_diary_entries_client_entry_id");

                    b.HasIndex("LocalTimestamp")
                        .HasDatabaseName("ix_diary_entries_local_timestamp");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_diary_entries_patient_id");

                    b.ToTable("diary_entries", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.IntakeBodyResponse.Domain.Model.Aggregates.SelfWeighIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientEntryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("client_entry_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LocalTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("local_timestamp");

                    b.Property<int>("LocalUtcOffsetMinutes")
                        .HasColumnType("int")
                        .HasColumnName("local_utc_offset_minutes");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<bool>("ProtocolFastedState")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("protocol_fasted_state");

                    b.Property<bool?>("ProtocolSameScale")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("protocol_same_scale");

                    b.Property<bool?>("ProtocolSameTimeOfDay")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("protocol_same_time_of_day");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("ValueKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("value_kg");

                    b.HasKey("Id")
                        .HasName("p_k_self_weigh_ins");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_self_weigh_ins_patient_id");

                    b.HasIndex("PatientId", "ClientEntryId")
                        .IsUnique()
                        .HasDatabaseName("ix_self_weigh_ins_patient_id_client_entry_id");

                    b.ToTable("self_weigh_ins", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.IntakeBodyResponse.Domain.Model.Aggregates.WeightTrend", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastRecalculatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_recalculated_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("WindowSize")
                        .HasColumnType("int")
                        .HasColumnName("window_size");

                    b.Property<string>("_points")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("points");

                    b.HasKey("PatientId")
                        .HasName("p_k_weight_trends");

                    b.ToTable("weight_trends", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.MonitoringAdherence.Domain.Model.Aggregates.ConsistencyIndex", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset?>("AlertSinceAt")
                        .HasColumnType("datetime")
                        .HasColumnName("alert_since_at");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EscalatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("escalated_at");

                    b.Property<DateTimeOffset?>("FirstFlaggedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("first_flagged_at");

                    b.Property<DateTimeOffset>("LastRecomputedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_recomputed_at");

                    b.Property<DateTimeOffset?>("PromptIssuedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("prompt_issued_at");

                    b.Property<DateTimeOffset?>("ShownToPatientAt")
                        .HasColumnType("datetime")
                        .HasColumnName("shown_to_patient_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("value");

                    b.HasKey("PatientId")
                        .HasName("p_k_consistency_indices");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_consistency_indices_state");

                    b.ToTable("consistency_indices", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.MonitoringAdherence.Domain.Model.Aggregates.Deviation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("detected_at");

                    b.Property<int>("DeviatingDaysConsidered")
                        .HasColumnType("int")
                        .HasColumnName("deviating_days_considered");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("direction");

                    b.Property<bool>("IsSustained")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_sustained");

                    b.Property<int>("LoggedDaysConsidered")
                        .HasColumnType("int")
                        .HasColumnName("logged_days_considered");

                    b.Property<decimal>("MagnitudeEnergyKcal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("magnitude_energy_kcal");

                    b.Property<decimal>("MagnitudeRelativeValue")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("magnitude_relative_value");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset?>("SustainedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("sustained_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("WindowRef")
                        .HasColumnType("int")
                        .HasColumnName("window_id");

                    b.HasKey("Id")
                        .HasName("p_k_deviations");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_deviations_patient_id");

                    b.HasIndex("WindowRef")
                        .HasDatabaseName("ix_deviations_window_id");

                    b.ToTable("deviations", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.MonitoringAdherence.Domain.Model.Aggregates.EvaluationWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CareLinkId")
                        .HasColumnType("int")
                        .HasColumnName("care_link_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("from_date");

                    b.Property<DateTime?>("LastLoggingGapFlaggedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_logging_gap_flagged_on");

                    b.Property<DateTimeOffset?>("LastPatientRemindedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_patient_reminded_at");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("state");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("to_date");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("WindowDays")
                        .HasColumnType("int")
                        .HasColumnName("window_days");

                    b.Property<string>("_anthropometrySeries")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("anthropometry_series");

                    b.Property<string>("_dailyComplianceSeries")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("daily_compliance_series");

                    b.Property<string>("_targetsSnapshots")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("targets_snapshots");

                    b.HasKey("Id")
                        .HasName("p_k_evaluation_windows");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_evaluation_windows_patient_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_evaluation_windows_state");

                    b.ToTable("evaluation_windows", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.MonitoringAdherence.Domain.Model.Aggregates.PreVisitCheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("edited_at");

                    b.Property<string>("Feeling")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("feeling");

                    b.Property<int>("FollowUpId")
                        .HasColumnType("int")
                        .HasColumnName("follow_up_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("int")
                        .HasColumnName("practitioner_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("submitted_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("_difficulties")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("difficulties");

                    b.Property<string>("_questions")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("questions");

                    b.HasKey("Id")
                        .HasName("p_k_pre_visit_check_ins");

                    b.HasIndex("FollowUpId")
                        .IsUnique()
                        .HasDatabaseName("ux_pre_visit_check_ins_follow_up_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_pre_visit_check_ins_patient_id");

                    b.ToTable("pre_visit_check_ins", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.MonitoringAdherence.Domain.Model.Aggregates.Referral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("issued_at");

                    b.Property<int>("IssuedBy")
                        .HasColumnType("int")
                        .HasColumnName("issued_by");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("specialty");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Open")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_referrals");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_referrals_patient_id");

                    b.ToTable("referrals", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.MonitoringAdherence.Domain.Model.Aggregates.ScheduledFollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetime")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at");

                    b.Property<int?>("CompletedByConsultationId")
                        .HasColumnType("int")
                        .HasColumnName("completed_by_consultation_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("MissedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("missed_at");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("modality");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("int")
                        .HasColumnName("practitioner_id");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("datetime")
                        .HasColumnName("scheduled_for");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("_preparation")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("preparation");

                    b.HasKey("Id")
                        .HasName("p_k_scheduled_follow_ups");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_scheduled_follow_ups_patient_id");

                    b.HasIndex("PractitionerId")
                        .HasDatabaseName("ix_scheduled_follow_ups_practitioner_id");

                    b.ToTable("scheduled_follow_ups", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.NutritionalCare.Domain.Model.Aggregates.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AbandonedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("abandoned_at");

                    b.Property<int?>("AssessmentId")
                        .HasColumnType("int")
                        .HasColumnName("assessment_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("current_step");

                    b.Property<int?>("DiagnosisId")
                        .HasColumnType("int")
                        .HasColumnName("diagnosis_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<int?>("InProgressPatientId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("in_progress_patient_id")
                        .HasComputedColumnSql("IF(`state` = 'InProgress', `patient_id`, NULL)", true);

                    b.Property<bool>("IsFirstConsultation")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_first_consultation");

                    b.Property<DateTimeOffset>("LastSavedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_saved_at");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("int")
                        .HasColumnName("practitioner_id");

                    b.Property<string>("PublicationDraft")
                        .HasColumnType("json")
                        .HasColumnName("publication_draft");

                    b.Property<int?>("PublishedPlanVersion")
                        .HasColumnType("int")
                        .HasColumnName("published_plan_version");

                    b.Property<int?>("ScheduledFollowUpId")
                        .HasColumnType("int")
                        .HasColumnName("scheduled_follow_up_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_consultations");

                    b.HasIndex("InProgressPatientId")
                        .IsUnique()
                        .HasDatabaseName("ix_consultations_in_progress_patient_id");

                    b.HasIndex("PatientId", "State")
                        .HasDatabaseName("ix_consultations_patient_id_state");

                    b.ToTable("consultations", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.NutritionalCare.Domain.Model.Aggregates.NutritionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("BasisActivityFactor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("basis_activity_factor");

                    b.Property<decimal>("BasisComputedBmr")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("basis_computed_bmr");

                    b.Property<decimal>("BasisComputedTdee")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("basis_computed_tdee");

                    b.Property<string>("BasisDeficitKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("basis_deficit_kind");

                    b.Property<decimal>("BasisDeficitValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("basis_deficit_value");

                    b.Property<string>("BasisEquation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("basis_equation");

                    b.Property<decimal>("BasisReferenceWeightKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("basis_reference_weight_kg");

                    b.Property<string>("BasisReferenceWeightKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("basis_reference_weight_kind");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("change_reason");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int")
                        .HasColumnName("diagnosis_id");

                    b.Property<DateTimeOffset?>("DiscardedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("discarded_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<string>("PatientMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("patient_message");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("int")
                        .HasColumnName("practitioner_id");

                    b.Property<decimal?>("PrescribedCarbG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("prescribed_carb_g");

                    b.Property<decimal?>("PrescribedEnergyKcal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("prescribed_energy_kcal");

                    b.Property<decimal?>("PrescribedFatG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("prescribed_fat_g");

                    b.Property<string>("PrescribedOutcome")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("prescribed_outcome");

                    b.Property<string>("PrescribedOverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("prescribed_override_reason");

                    b.Property<decimal?>("PrescribedProteinG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("prescribed_protein_g");

                    b.Property<decimal>("ProposalCarbG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("proposal_carb_g");

                    b.Property<decimal>("ProposalEnergyKcal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("proposal_energy_kcal");

                    b.Property<decimal>("ProposalFatG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("proposal_fat_g");

                    b.Property<decimal>("ProposalProteinG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("proposal_protein_g");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("datetime")
                        .HasColumnName("superseded_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.Property<string>("_changesFromPrevious")
                        .HasColumnType("json")
                        .HasColumnName("patient_change_summary");

                    b.Property<string>("_droppedLegacyRestrictions")
                        .HasColumnType("json")
                        .HasColumnName("dropped_legacy_restrictions");

                    b.Property<string>("_guidelines")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("guidelines");

                    b.Property<string>("_legacyRestrictions")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("legacy_restrictions");

                    b.Property<string>("_restrictions")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("restrictions");

                    b.HasKey("Id")
                        .HasName("p_k_nutrition_plans");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_nutrition_plans_patient_id");

                    b.ToTable("nutrition_plans", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.NutritionalCare.Domain.Model.Aggregates.NutritionalAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("activity_level");

                    b.Property<int>("AgeYears")
                        .HasColumnType("int")
                        .HasColumnName("age_years");

                    b.Property<string>("Biochemistry")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("biochemistry");

                    b.Property<string>("BiologicalSex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("biological_sex");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("closed_at");

                    b.Property<int?>("ConsultationId")
                        .HasColumnType("int")
                        .HasColumnName("consultation_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("FastingGlucoseMgDl")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("glucose_mg_dl");

                    b.Property<string>("Habits")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("habits");

                    b.Property<int?>("MealsOutPerWeek")
                        .HasColumnType("int")
                        .HasColumnName("meals_out_per_week");

                    b.Property<int?>("MealsPerDay")
                        .HasColumnType("int")
                        .HasColumnName("meals_per_day");

                    b.Property<string>("MedicalHistory")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("medical_history");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<string>("PhysicalActivity")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("physical_activity");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("int")
                        .HasColumnName("practitioner_id");

                    b.Property<int?>("SupersedesAssessmentId")
                        .HasColumnType("int")
                        .HasColumnName("supersedes_assessment_id");

                    b.Property<decimal?>("TotalCholesterolMgDl")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("total_cholesterol_mg_dl");

                    b.Property<decimal?>("TriglyceridesMgDl")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("triglycerides_mg_dl");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("WaterLitersPerDay")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("water_liters_per_day");

                    b.Property<string>("_conditionsSnapshot")
                        .HasColumnType("json")
                        .HasColumnName("conditions_snapshot");

                    b.HasKey("Id")
                        .HasName("p_k_nutritional_assessments");

                    b.HasIndex("ConsultationId")
                        .HasDatabaseName("ix_nutritional_assessments_consultation_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_nutritional_assessments_patient_id");

                    b.ToTable("nutritional_assessments", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.NutritionalCare.Domain.Model.Aggregates.NutritionalDiagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<long?>("AiGenerationId")
                        .HasColumnType("bigint")
                        .HasColumnName("ai_generation_id");

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int")
                        .HasColumnName("assessment_id");

                    b.Property<decimal?>("BmiAtIssue")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("bmi_at_issue");

                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DiscardedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("discarded_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("issued_at");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<int?>("PendingConsultationId")
                        .HasColumnType("int")
                        .HasColumnName("pending_consultation_id");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("int")
                        .HasColumnName("practitioner_id");

                    b.Property<string>("Rationale")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("rationale");

                    b.Property<string>("Source")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("source");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("statement");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("datetime")
                        .HasColumnName("superseded_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_nutritional_diagnoses");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_nutritional_diagnoses_patient_id");

                    b.HasIndex("PendingConsultationId")
                        .HasDatabaseName("ix_nutritional_diagnoses_pending_consultation_id");

                    b.ToTable("nutritional_diagnoses", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.NutritionalCare.Domain.Model.Aggregates.PatientBaseline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("BiologicalSex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("biological_sex");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<bool>("BirthDateEstimated")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("birth_date_estimated");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("height_cm");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<int>("RecordedBy")
                        .HasColumnType("int")
                        .HasColumnName("recorded_by");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("_conditions")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("conditions");

                    b.HasKey("Id")
                        .HasName("p_k_patient_baselines");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasDatabaseName("ix_patient_baselines_patient_id");

                    b.ToTable("patient_baselines", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.NutritionalCare.Domain.Model.Aggregates.ReviewItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("evidence");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("int")
                        .HasColumnName("practitioner_id");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("resolved_at");

                    b.Property<bool?>("ResolvedWithAdjustment")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("resolved_with_adjustment");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("signal_type");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_review_items");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_review_items_patient_id");

                    b.HasIndex("PractitionerId")
                        .HasDatabaseName("ix_review_items_practitioner_id");

                    b.ToTable("review_items", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.NutritionalCare.Domain.Model.Entities.ClinicalMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int")
                        .HasColumnName("assessment_id");

                    b.Property<string>("BmiCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("bmi_category");

                    b.Property<decimal>("BmiKgM2")
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("bmi");

                    b.Property<decimal?>("BodyFatPercentage")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("body_fat_percentage");

                    b.Property<decimal>("HeightCm")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("height_cm");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("protocol");

                    b.Property<DateTimeOffset>("TakenAt")
                        .HasColumnType("datetime")
                        .HasColumnName("taken_at");

                    b.Property<decimal?>("WaistCircumferenceCm")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("waist_circumference_cm");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("weight_kg");

                    b.Property<string>("_protocolChecks")
                        .HasColumnType("json")
                        .HasColumnName("protocol_checks");

                    b.HasKey("Id")
                        .HasName("p_k_clinical_measurements");

                    b.HasIndex("AssessmentId")
                        .HasDatabaseName("ix_clinical_measurements_assessment_id");

                    b.ToTable("clinical_measurements", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.NutritionalCare.Domain.Model.Entities.ClinicalMeasurement", b =>
                {
                    b.HasOne("Healthify.Platform.NutritionalCare.Domain.Model.Aggregates.NutritionalAssessment", null)
                        .WithMany("Measurements")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_clinical_measurements_nutritional_assessments_assessment_id");
                });

            modelBuilder.Entity("Healthify.Platform.NutritionalCare.Domain.Model.Aggregates.NutritionalAssessment", b =>
                {
                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
