// <auto-generated />
using System;
using Healthify.Platform.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Healthify.Platform.Shared.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904123002_FoodCatalog_InitialCreate")]
    partial class FoodCatalog_InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Healthify.Platform.CareRelationship.Domain.Model.Aggregates.CareLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("ConsentGranted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("consent_granted");

                    b.Property<DateTimeOffset?>("ConsentGrantedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("consent_granted_at");

                    b.Property<string>("ConsentScope")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("consent_scope");

                    b.Property<DateTimeOffset?>("ConsentWithdrawnAt")
                        .HasColumnType("datetime")
                        .HasColumnName("consent_withdrawn_at");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DischargeReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("discharge_reason");

                    b.Property<DateTimeOffset?>("DischargedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("discharged_at");

                    b.Property<DateTimeOffset>("EstablishedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("established_at");

                    b.Property<int?>("LastAcknowledgedVersion")
                        .HasColumnType("int")
                        .HasColumnName("last_acknowledged_version");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<int?>("PendingTargetsVersion")
                        .HasColumnType("int")
                        .HasColumnName("pending_targets_version");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("int")
                        .HasColumnName("practitioner_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_care_links");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_care_links_patient_id");

                    b.HasIndex("PractitionerId")
                        .HasDatabaseName("ix_care_links_practitioner_id");

                    b.ToTable("care_links", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.CareRelationship.Domain.Model.Aggregates.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expired_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<int>("IssuedBy")
                        .HasColumnType("int")
                        .HasColumnName("issued_by");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("redeemed_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_invitations");

                    b.HasIndex("IssuedBy")
                        .HasDatabaseName("ix_invitations_issued_by");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_invitations_token");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.FoodCatalog.Domain.Model.Aggregates.ReferenceFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("CarbGPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("carb_g_per_100g");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EnergyKcalPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("energy_kcal_per_100g");

                    b.Property<decimal>("FatGPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("fat_g_per_100g");

                    b.Property<bool>("IsLocalOverride")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_local_override");

                    b.Property<string>("LocalNameText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("local_name");

                    b.Property<decimal>("ProteinGPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("protein_g_per_100g");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_reference_foods");

                    b.HasIndex("LocalNameText")
                        .HasDatabaseName("ix_reference_foods_local_name");

                    b.HasIndex("SourceHash")
                        .IsUnique()
                        .HasDatabaseName("ix_reference_foods_source_hash");

                    b.ToTable("reference_foods", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int>("FailedSignInAttempts")
                        .HasColumnType("int")
                        .HasColumnName("failed_sign_in_attempts");

                    b.Property<DateTimeOffset?>("LockedOutAt")
                        .HasColumnType("datetime")
                        .HasColumnName("locked_out_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.Iam.Domain.Model.Aggregates.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("NavigationShell")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("navigation_shell");

                    b.Property<string>("RoleClaim")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role_claim");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset?>("TerminatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("terminated_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.NutritionalCare.Domain.Model.Aggregates.NutritionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("BasisActivityFactor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("basis_activity_factor");

                    b.Property<decimal>("BasisComputedBmr")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("basis_computed_bmr");

                    b.Property<decimal>("BasisComputedTdee")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("basis_computed_tdee");

                    b.Property<string>("BasisDeficitKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("basis_deficit_kind");

                    b.Property<decimal>("BasisDeficitValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("basis_deficit_value");

                    b.Property<string>("BasisEquation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("basis_equation");

                    b.Property<decimal>("BasisReferenceWeightKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("basis_reference_weight_kg");

                    b.Property<string>("BasisReferenceWeightKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("basis_reference_weight_kind");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("change_reason");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int")
                        .HasColumnName("diagnosis_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("int")
                        .HasColumnName("practitioner_id");

                    b.Property<decimal?>("PrescribedCarbG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("prescribed_carb_g");

                    b.Property<decimal?>("PrescribedEnergyKcal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("prescribed_energy_kcal");

                    b.Property<decimal?>("PrescribedFatG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("prescribed_fat_g");

                    b.Property<string>("PrescribedOutcome")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("prescribed_outcome");

                    b.Property<string>("PrescribedOverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("prescribed_override_reason");

                    b.Property<decimal?>("PrescribedProteinG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("prescribed_protein_g");

                    b.Property<decimal>("ProposalCarbG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("proposal_carb_g");

                    b.Property<decimal>("ProposalEnergyKcal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("proposal_energy_kcal");

                    b.Property<decimal>("ProposalFatG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("proposal_fat_g");

                    b.Property<decimal>("ProposalProteinG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("proposal_protein_g");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("datetime")
                        .HasColumnName("superseded_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.Property<string>("_guidelines")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("guidelines");

                    b.Property<string>("_restrictions")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("restrictions");

                    b.HasKey("Id")
                        .HasName("p_k_nutrition_plans");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_nutrition_plans_patient_id");

                    b.ToTable("nutrition_plans", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.NutritionalCare.Domain.Model.Aggregates.NutritionalAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AgeYears")
                        .HasColumnType("int")
                        .HasColumnName("age_years");

                    b.Property<string>("Biochemistry")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("biochemistry");

                    b.Property<string>("BiologicalSex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("biological_sex");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Habits")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("habits");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("medical_history");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<string>("PhysicalActivity")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("physical_activity");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("int")
                        .HasColumnName("practitioner_id");

                    b.Property<int?>("SupersedesAssessmentId")
                        .HasColumnType("int")
                        .HasColumnName("supersedes_assessment_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_nutritional_assessments");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_nutritional_assessments_patient_id");

                    b.ToTable("nutritional_assessments", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.NutritionalCare.Domain.Model.Aggregates.NutritionalDiagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int")
                        .HasColumnName("assessment_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("issued_at");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("int")
                        .HasColumnName("practitioner_id");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("rationale");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("statement");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("datetime")
                        .HasColumnName("superseded_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_nutritional_diagnoses");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_nutritional_diagnoses_patient_id");

                    b.ToTable("nutritional_diagnoses", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.NutritionalCare.Domain.Model.Aggregates.ReviewItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("evidence");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<int>("PractitionerId")
                        .HasColumnType("int")
                        .HasColumnName("practitioner_id");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("resolved_at");

                    b.Property<bool?>("ResolvedWithAdjustment")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("resolved_with_adjustment");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("signal_type");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_review_items");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_review_items_patient_id");

                    b.HasIndex("PractitionerId")
                        .HasDatabaseName("ix_review_items_practitioner_id");

                    b.ToTable("review_items", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.NutritionalCare.Domain.Model.Entities.ClinicalMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int")
                        .HasColumnName("assessment_id");

                    b.Property<decimal?>("BodyFatPercentage")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("body_fat_percentage");

                    b.Property<decimal>("HeightCm")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("height_cm");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("protocol");

                    b.Property<DateTimeOffset>("TakenAt")
                        .HasColumnType("datetime")
                        .HasColumnName("taken_at");

                    b.Property<decimal?>("WaistCircumferenceCm")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("waist_circumference_cm");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("p_k_clinical_measurements");

                    b.HasIndex("AssessmentId")
                        .HasDatabaseName("ix_clinical_measurements_assessment_id");

                    b.ToTable("clinical_measurements", (string)null);
                });

            modelBuilder.Entity("Healthify.Platform.NutritionalCare.Domain.Model.Entities.ClinicalMeasurement", b =>
                {
                    b.HasOne("Healthify.Platform.NutritionalCare.Domain.Model.Aggregates.NutritionalAssessment", null)
                        .WithMany("Measurements")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_clinical_measurements_nutritional_assessments_assessment_id");
                });

            modelBuilder.Entity("Healthify.Platform.NutritionalCare.Domain.Model.Aggregates.NutritionalAssessment", b =>
                {
                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
